axis_linear: 1  # Left thumb stick vertical
scale_linear: 0.5
scale_linear_turbo: 0.7

axis_angular: 0  # Left thumb stick horizontal
scale_angular: 2.0
scale_angular_turbo: 4.0

enable_button: 2  # Left trigger button
enable_turbo_button: 5  # Right trigger button
